# Generated by scripts/update.sh — don't edit by hand.
cask "xpress" do
  arch arm: "aarch64", intel: "x86_64"

  version "1.0.0"
  sha256 arm:   "b7185d1d2c9fdac657b3be4a5812bfe2e1364288048b67b12e50a0e579bb8f39",
         intel: "8d0cf7012268f438879b90a9a37277e3a2f7171d0abf9eac50d8b4317b59a2da"

  url "https://github.com/kwhorne/xpress/releases/download/v#{version}/xpress-v#{version}-macos-#{arch}-apple-darwin.dmg"
  name "xpress"
  desc "Menu-bar app that makes images, video, PDFs and audio smaller"
  homepage "https://github.com/kwhorne/xpress"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself (Update & Restart).
  auto_updates true
  depends_on macos: :big_sur

  app "xpress.app"

  zap trash: [
    "~/Library/Application Support/xpress",
  ]
end
