# Generated by scripts/update.sh — don't edit by hand.
cask "xpress" do
  version "0.9.2"
  sha256 "e10a684cebab51847bf808c8e8564a23e69d4f32bb8e0364527c31cd8d9a8415"

  url "https://github.com/kwhorne/xpress/releases/download/v#{version}/xpress-v#{version}-macos-aarch64-apple-darwin.dmg"
  name "xpress"
  desc "Menu-bar app that makes images, video, PDFs and audio smaller"
  homepage "https://github.com/kwhorne/xpress"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself (Update & Restart).
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :big_sur

  app "xpress.app"

  zap trash: [
    "~/Library/Application Support/xpress",
  ]
end
