# Generated by scripts/update.sh — don't edit by hand.
cask "xpress" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.9.3"
  sha256 arm:   "bae54d042e8114b7ebe7e01627a8d3401ff64da07a417a7b1d2119cbb2ad0125",
         intel: "f1e7114e08e78aa9f894f20cf3a8b7a3742628b88bd184a47eb1d1c80096ca21"

  url "https://github.com/kwhorne/xpress/releases/download/v#{version}/xpress-v#{version}-macos-#{arch}-apple-darwin.dmg"
  name "xpress"
  desc "Menu-bar app that makes images, video, PDFs and audio smaller"
  homepage "https://github.com/kwhorne/xpress"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself (Update & Restart).
  auto_updates true
  depends_on macos: :big_sur

  app "xpress.app"

  zap trash: [
    "~/Library/Application Support/xpress",
  ]
end
