# Generated by scripts/update.sh — don't edit by hand.
class Xpress < Formula
  desc "Make images, video, PDFs and audio smaller"
  homepage "https://github.com/kwhorne/xpress"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/kwhorne/xpress/releases/download/v0.8.3/xpress-v0.8.3-aarch64-apple-darwin.tar.gz"
      sha256 "23835cd9a2525559a2dd9004f3d47a6dd869c439a0ba93710943d35c0febf77f"
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      url "https://github.com/kwhorne/xpress/releases/download/v0.8.3/xpress-v0.8.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "98b57437ab29b9d52c6311133b874f0c61b196c3a754504bbca033e5f2f74708"
    end
  end

  def install
    bin.install "xpress"
    generate_completions_from_executable(bin/"xpress", "completions")
    (man1/"xpress.1").write Utils.safe_popen_read(bin/"xpress", "man")
  end

  def caveats
    <<~EOS
      Video and audio need ffmpeg:  brew install ffmpeg
      The desktop app:              brew install --cask kwhorne/tap/xpress
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xpress --version")
    (testpath/"a.txt").write "not media"
    assert_match "no optimisable files", shell_output("#{bin}/xpress optimise #{testpath}/a.txt 2>&1", 1)
  end
end
