# Generated by scripts/update.sh — don't edit by hand.
class Xpress < Formula
  desc "Make images, video, PDFs and audio smaller"
  homepage "https://github.com/kwhorne/xpress"
  license "MIT"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/kwhorne/xpress/releases/download/v0.9.2/xpress-v0.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "23a6b75868b79999c0202fb644fc6768843aeefe20adb1c7d036422e1531775a"
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      url "https://github.com/kwhorne/xpress/releases/download/v0.9.2/xpress-v0.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "68af54a62822ddaf3df43b3bf6a759fda2dd67ffd8facbd810c75a2509d0938f"
    end
  end

  def install
    bin.install "xpress"
    generate_completions_from_executable(bin/"xpress", "completions")
    (man1/"xpress.1").write Utils.safe_popen_read(bin/"xpress", "man")
  end

  def caveats
    <<~EOS
      Video and audio need ffmpeg:  brew install ffmpeg
      The desktop app:              brew install --cask kwhorne/tap/xpress
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xpress --version")
    (testpath/"a.txt").write "not media"
    assert_match "no optimisable files", shell_output("#{bin}/xpress optimise #{testpath}/a.txt 2>&1", 1)
  end
end
