#!/usr/bin/env bash
#
# Write Formula/xpress.rb and Casks/xpress.rb for an xpress release: the
# latest one, or the tag given (e.g. v0.8.3). Checksums come from the
# release's .sha256 files.

set -euo pipefail
cd "$(dirname "$0")/.."

REPO="kwhorne/xpress"
BASE="https://github.com/$REPO/releases"
TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  # The latest release, from the redirect (no API, no rate limit).
  TAG="$(curl -fsSI "$BASE/latest" | tr -d '\r' | sed -n 's#^location: .*/tag/##Ip' | tail -1)"
fi
[[ "$TAG" == v* ]] || { echo "no release tag found (got '$TAG')" >&2; exit 1; }
VERSION="${TAG#v}"

sha() {
  curl -fsSL "$BASE/download/$TAG/$1.sha256" | awk '{print $1}'
}
MAC="$(sha "xpress-$TAG-aarch64-apple-darwin.tar.gz")"
LINUX="$(sha "xpress-$TAG-x86_64-unknown-linux-gnu.tar.gz")"
DMG="$(sha "xpress-$TAG-macos-aarch64-apple-darwin.dmg")"
for s in "$MAC" "$LINUX" "$DMG"; do
  [[ "$s" =~ ^[0-9a-f]{64}$ ]] || { echo "bad checksum '$s' for $TAG" >&2; exit 1; }
done

cat > Formula/xpress.rb <<EOF
# Generated by scripts/update.sh — don't edit by hand.
class Xpress < Formula
  desc "Make images, video, PDFs and audio smaller"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    url "$BASE/download/$TAG/xpress-$TAG-aarch64-apple-darwin.tar.gz"
    sha256 "$MAC"
  end

  on_linux do
    depends_on arch: :x86_64
    url "$BASE/download/$TAG/xpress-$TAG-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "$LINUX"
  end

  def install
    bin.install "xpress"
    generate_completions_from_executable(bin/"xpress", "completions")
    (man1/"xpress.1").write Utils.safe_popen_read(bin/"xpress", "man")
  end

  def caveats
    <<~EOS
      Video and audio need ffmpeg:  brew install ffmpeg
      The desktop app:              brew install --cask kwhorne/tap/xpress
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/xpress --version")
    (testpath/"a.txt").write "not media"
    assert_match "no optimisable files", shell_output("#{bin}/xpress optimise #{testpath}/a.txt 2>&1", 1)
  end
end
EOF

cat > Casks/xpress.rb <<EOF
# Generated by scripts/update.sh — don't edit by hand.
cask "xpress" do
  version "$VERSION"
  sha256 "$DMG"

  url "$BASE/download/v#{version}/xpress-v#{version}-macos-aarch64-apple-darwin.dmg"
  name "xpress"
  desc "Menu-bar app that makes images, video, PDFs and audio smaller"
  homepage "https://github.com/$REPO"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself (Update & Restart).
  auto_updates true
  depends_on arch: :arm64
  depends_on macos: ">= :big_sur"

  app "xpress.app"

  zap trash: [
    "~/Library/Application Support/xpress",
  ]
end
EOF
echo "xpress $VERSION"
